### ISSUE TITLE
import ptitprince as pt error in python

### ISSUE THREAD

**Issue by qgehmacher** [RainCloudPlots/RainCloudPlots#45]
Throws 'ImportError: cannot import name 'categorical_order' from 'seaborn.utils'

seaborn.utils does not have 'categorical_order' defined at all...also Ptitprince.py does not use 'categorical_order' at all in the code
 Fix: Simply remove categorical_order from Ptitprince.py line 20 'from seaborn.utils import iqr, categorical_order, remove_na'

Traceback (most recent call last):
  File "/home/X/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-04fe9a0a6e24>", line 1, in <module>
    import ptitprince as pt
  File "/snap/pycharm-community/214/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/X/anaconda3/lib/python3.7/site-packages/ptitprince/__init__.py", line 1, in <module>
    from .PtitPrince import half_violinplot, RainCloud, stripplot
  File "/snap/pycharm-community/214/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/X/anaconda3/lib/python3.7/site-packages/ptitprince/PtitPrince.py", line 20, in <module>
    from seaborn.utils import iqr, categorical_order, remove_na
ImportError: cannot import name 'categorical_order' from 'seaborn.utils'

**Comment by pog87** [comment]
try and refer to

https://github.com/pog87/PtitPrince/issues/16#issuecomment-701225906
